version: "2"

services:
  gql:
    build: .
    command: "go run entry.go"
    ports:
      - "8090:8090"
    volumes:
      - ".:/go/src/github.com/dbinnersley/graphql-sample"
    links:
      - mysql

  mysql:
    image : mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
    ports:
      - "3306:3306"